### PR TITLE
fix: Use custom error types in the builder

### LINKED ISSUE #1478: Use custom WrappableError types in the docker builder
nit: In general, I think we'd prefer to check errors based on their type rather than the error message string.

See the `WrappableError` type
https://github.com/slsa-framework/slsa-github-generator/blob/1ed3657976aadcbd9fe3aaf2117d315e0a934e97/internal/errors/wrappable.go

some examples where it's used
https://github.com/slsa-framework/slsa-github-generator/blob/1ed3657976aadcbd9fe3aaf2117d315e0a934e97/internal/builders/generic/generic.go#L59-L82

and some tests where it's checked
https://github.com/slsa-framework/slsa-github-generator/blob/1ed3657976aadcbd9fe3aaf2117d315e0a934e97/internal/builders/generic/attest_test.go#L26

_Originally posted by @ianlewis in https://github.com/slsa-framework/slsa-github-generator/pull/1388#discussion_r1063417838_

### PR DESCRIPTION
**Pull request by rbehjati**
Fixes #1478.

Signed-off-by: Razieh Behjati <razieh@google.com>

### CODE REVIEW

File: internal/builders/docker/pkg/builder_test.go [hunk 1]
```diff
@@ -15,13 +15,12 @@
...
 
 import (
-	"fmt"
 	"os"
-	"strings"
 	"testing"
 
 	"github.com/google/go-cmp/cmp"
 	intoto "github.com/in-toto/in-toto-golang/in_toto"
+	"github.com/slsa-framework/slsa-github-generator/internal/errors"
```
Comment (ianlewis) [inline internal/builders/docker/pkg/builder_test.go:23]: Add a space so project imports aren't lumped in with 3rd party ones.

```suggestion
	"github.com/google/go-cmp/cmp"
	intoto "github.com/in-toto/in-toto-golang/in_toto"

	"github.com/slsa-framework/slsa-github-generator/internal/errors"
```

File: internal/builders/docker/pkg/builder.go [hunk 2]
```diff
@@ -36,8 +36,24 @@ import (
 	"strings"
 
 	intoto "github.com/in-toto/in-toto-golang/in_toto"
+	"github.com/slsa-framework/slsa-github-generator/internal/errors"
```
Comment (ianlewis) [inline internal/builders/docker/pkg/builder.go:39]: Add a space so project imports aren't lumped in with 3rd party ones.
```suggestion
	intoto "github.com/in-toto/in-toto-golang/in_toto"

	"github.com/slsa-framework/slsa-github-generator/internal/errors"
```

File: internal/builders/docker/pkg/builder_test.go [hunk 3]
```diff
@@ -157,13 +156,8 @@ func Test_Builder_SetUpBuildState(t *testing.T) {
...
-// TODO(#1478): Use custom error types, and check errors based on their type.
-func checkError(t *testing.T, err error, want string) {
-	if err == nil {
-		t.Errorf("expected error, got nil")
-	}
-	got := fmt.Sprintf("%v", err)
-	if !strings.Contains(got, want) {
-		t.Errorf("unexpected error message: got (%q) does not contain want (%q)", got, want)
+func checkError(t *testing.T, got error, want any) {
+	if !errors.As(got, &want) {
```
Comment (ianlewis) [inline internal/builders/docker/pkg/builder_test.go:160]: Unfortunately, `errors.As` in Go 1.19+ is a bit finicky. Right now this will pass for any input of `want`.
https://go.dev/play/p/hZcplmSC3lx

Unfortunately you need to implement a function per type you want to check as was done here
https://github.com/slsa-framework/slsa-github-generator/blob/4c2f963dd197da76843196f9830051d772d8efc2/internal/builders/generic/attest_test.go#L27-L32
See: https://go.dev/play/p/YuY_OIVNtcF

**Review by ianlewis — COMMENTED** [review]
Thanks for doing this!

File: internal/builders/docker/pkg/builder.go (hunk 2 above)
Comment (rbehjati) [reply internal/builders/docker/pkg/builder.go]: Thanks. Done.

File: internal/builders/docker/pkg/builder_test.go (hunk 1 above)
Comment (rbehjati) [reply internal/builders/docker/pkg/builder_test.go]: Done.

File: internal/builders/docker/pkg/builder_test.go (hunk 3 above)
Comment (rbehjati) [reply internal/builders/docker/pkg/builder_test.go:162]: Thanks for pointing this out. I have now made `checkError` generic. So now it fails if the wrong error type is used.

**Review by rbehjati — COMMENTED** [review]
Thanks for the review.

**Comment by rbehjati** [comment]
@ianlewis There is a PR title failure now. How can I fix that?

**Comment by asraa** [comment]
> @ianlewis There is a PR title failure now. How can I fix that?

Update to something like `fix: Use custom error types in the builder` (we use https://www.conventionalcommits.org/en/v1.0.0/#summary)

**Comment by rbehjati** [comment]
> > @ianlewis There is a PR title failure now. How can I fix that?
> 
> Update to something like `fix: Use custom error types in the builder` (we use https://www.conventionalcommits.org/en/v1.0.0/#summary)
 
Thanks :)

File: internal/builders/docker/pkg/builder.go [hunk 4]
```diff
@@ -340,7 +358,7 @@ func (c *GitClient) fetchSourcesFromGitRepo() error {
 
 	// Checkout the commit.
 	if err = c.checkoutGitCommit(); err != nil {
-		return fmt.Errorf("couldn't checkout the Git commit: %v", err)
+		return errors.Errorf(&errGitCheckout{}, "couldn't checkout the Git commit: %v", err)
```
Comment (ianlewis) [inline internal/builders/docker/pkg/builder.go:361]:
```suggestion
		return errors.Errorf(&errGitCheckout{}, "couldn't checkout the Git commit: %w", err)
```

File: internal/builders/docker/pkg/builder.go [hunk 5]
```diff
@@ -324,7 +342,7 @@ func (c *GitClient) fetchSourcesFromGitRepo() error {
 
 	// Clone the repo.
 	if err = c.cloneGitRepo(); err != nil {
-		return fmt.Errorf("couldn't clone the Git repo: %v", err)
+		return errors.Errorf(&errGitFetch{}, "couldn't clone the Git repo: %v", err)
```
Comment (ianlewis) [inline internal/builders/docker/pkg/builder.go:345]:
```suggestion
		return errors.Errorf(&errGitFetch{}, "couldn't clone the Git repo: %w", err)
```

File: internal/builders/docker/pkg/builder_test.go (hunk 3 above)
Comment (ianlewis) [reply internal/builders/docker/pkg/builder_test.go:162]: That's a good idea. I should probably update attest_test.go to use this method.

**Review by ianlewis — APPROVED** [review]
